# Download test data from: https://osf.io/tn4xj/

loaders:
  dataset: Kits19Dataset
  batch_size: 1
  mirror_padding:
  - 16
  - 32
  - 32
  num_workers: 8
  # directory where the output from the model will be saved
  output_dir: "/mnt/sda2/kits19_result"
  original_data_dir: "/mnt/sda2/kits19/data"
  raw_internal_path: raw
  test:
    file_paths:
    - "/mnt/sda2/kits19_processed/Test"
    slice_builder:
      name: SliceBuilder
      patch_shape:
      - 32
      - 144
      - 144
      stride_shape:
      - 20 
      - 80
      - 80
    transformer:
      raw:
      - name: Normalize
      - expand_dims: true
        name: ToTensor
manual_seed: 0
model:
  f_maps: 32
  final_sigmoid: true
  in_channels: 1
  is_segmentation: true
  layer_order: gcr
  name: UNet3D
  num_groups: 8
  out_channels: 1
model_path: "/mnt/sda2/kits19_processed/best_checkpoint.pytorch"
predictor:
  name: StandardPredictor
