# Download test data from: https://osf.io/tn4xj/

loaders:
  dataset: Kits19Dataset
  batch_size: 2 
  mirror_padding:
  - 16
  - 32
  - 32
  num_workers: 1
  # directory where the output from the model will be saved
  output_dir: "/mnt/sda2/kits19_processed/Result"
  original_data_dir: "/mnt/sda2/kits19/data"
  raw_internal_path: raw
  test:
    file_paths:
    - "/mnt/sda2/kits19_processed/Test"
    slice_builder:
      name: SliceBuilder
      patch_shape:
      - 60 
      - 130
      - 160
      stride_shape:
      - 50 
      - 110 
      - 140
    transformer:
      raw:
      - name: Standardize
      - expand_dims: true
        name: ToTensor
manual_seed: 0
model:
  f_maps: 32
  final_sigmoid: false 
  in_channels: 1
  is_segmentation: true
  layer_order: gcr
  name: UNet3D
  num_groups: 16 
  num_levels: 5
  out_channels: 3 
model_path: "/mnt/sda2/kits19_processed/last_checkpoint.pytorch"
predictor:
  name: StandardPredictorWithResample
  checkpoint_dir: "/mnt/sda2/kits19_processed"
visualize_output_dir: "/mnt/sda2/kits19_processed/img"
